# In order not to overlap with other applications.
server.port=9090

dou.training.set.csv.file.path=<dou training data set>
dou.regression.model.directory.path=<dou regression model>
dou.clustering.model.directory.path=<should be correct path used on different environments>

lyrics.training.set.directory.path=
lyrics.model.directory.path=
spark.local.dir.path=
# Selection from 5 possible pipelines: LogisticRegressionPipeline, NaiveBayesBagOfWordsPipeline, NaiveBayesTFIDFPipeline, RandomForestPipeline and FeedForwardNeuralNetworkPipeline
lyrics.pipeline=LogisticRegressionPipeline

mnist.training.set.image.file.path=<should be correct path used on different environments>
mnist.training.set.label.file.path=<should be correct path used on different environments>
mnist.test.set.image.file.path=<should be correct path used on different environments>
mnist.test.set.label.file.path=<should be correct path used on different environments>

mnist.training.set.parquet.file.path=<should be correct path used on different environments>
mnist.test.set.parquet.file.path=<should be correct path used on different environments>
mnist.model.directory.path=<should be correct path used on different environments>
mnist.validation.set.directory.path=<should be correct path used on different environments>

lyrics.model.file.csv = tcc_ceds_music.csv
product.training.set.csv.file.path=
product.test.set.csv.file.path=

training.validator.parallelism=7
